import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from 'next/font/google'
import StoreProvider from "./store/StoreProvider";


const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})
 
export const metadata: Metadata = {
  title: "Educore",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 return (
  <StoreProvider>
    <html lang="en" className={roboto.className}>
      <body>{children}</body>
    </html>
  </StoreProvider>
 );
}
